Repository Buzzpy/Dev-Encyclopedia, pull requests merged in 2024-08, with the labels that each got.

#67 Dark Mode - Issue #28 - Dark Mode Addition following Astro Integration
  .astro/astro/content.d.ts
  package-lock.json
  package.json
  public/hero-action.js
  src/components/Hero.astro
  src/styles/global.css
Labels: In Progress

#72 Autocomplete - Astro Integration
  package-lock.json
  package.json
  public/hero-action.js
  src/components/DevEncyclopedia.astro
  src/components/Hero.astro
  src/pages/api/json-files.js
  src/pages/index.astro
  src/styles/global.css
Labels: Outstanding Contribution ✨

#123 Code improvements
  public/card-actions.js
  src/components/CardList.astro
  src/components/DevEncyclopedia.astro
  src/components/Hero.astro
  src/components/Modal.astro
  src/layouts/BaseLayout.astro
  src/pages/index.astro
  src/scripts/cards.ts
  src/scripts/hero-action.js
  src/scripts/modal.ts
Labels: Testing
